version = 3
final_space = true

[palette]
  blue = '#8AADF4'
  frappe_bg = '#303446'
  frappe_black = '#292c3c'
  frappe_black4 = '#626880'
  frappe_blue = '#8caaee'
  frappe_cyan = '#99d1db'
  frappe_fg = '#c6d0f5'
  frappe_gray = '#414559'
  frappe_green = '#a6d189'
  frappe_magenta = '#ca9ee6'
  frappe_orange = '#ef9f76'
  frappe_pink = '#f4b8e4'
  frappe_red = '#e78284'
  frappe_yellow = '#e5c890'
  latte_bg = '#eff1f5'
  latte_black = '#e6e9ef'
  latte_black4 = '#acb0be'
  latte_blue = '#1e66f5'
  latte_cyan = '#04a5e5'
  latte_fg = '#4c4f69'
  latte_gray = '#ccd0da'
  latte_green = '#40a02b'
  latte_magenta = '#8839ef'
  latte_orange = '#fe640b'
  latte_pink = '#ea76cb'
  latte_red = '#d20f39'
  latte_yellow = '#df8e1d'
  lavender = '#B7BDF8'
  macchiato_bg = '#24273a'
  macchiato_black = '#1e2030'
  macchiato_black4 = '#5b6078'
  macchiato_blue = '#8aadf4'
  macchiato_cyan = '#91d7e3'
  macchiato_fg = '#cad3f5'
  macchiato_gray = '#363a4f'
  macchiato_green = '#a6da95'
  macchiato_magenta = '#c6a0f6'
  macchiato_orange = '#f5a97f'
  macchiato_pink = '#f5bde6'
  macchiato_red = '#ed8796'
  macchiato_yellow = '#eed49f'
  mocha_bg = '#1e1e2e'
  mocha_black = '#181825'
  mocha_black4 = '#585b70'
  mocha_blue = '#89b4fa'
  mocha_cyan = '#89dceb'
  mocha_fg = '#cdd6f4'
  mocha_gray = '#313244'
  mocha_green = '#a6e3a1'
  mocha_magenta = '#cba6f7'
  mocha_orange = '#fab387'
  mocha_pink = '#f5c2e7'
  mocha_red = '#f38ba8'
  mocha_yellow = '#f9e2af'
  orange = '#fab387'
  os = '#ACB0BE'
  pink = '#F5BDE6'
  text = '#494D64'
  wight = '#FFFFFF'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    template = '{{.Icon}} '
    foreground = 'p:text'
    background = 'p:frappe_magenta'
    type = 'os'
    style = 'diamond'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' {{ .Path }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:macchiato_orange'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = '....'
      home_icon = '~'
      style = 'agnoster_short'

  [[blocks.segments]]
    template = ' {{ .HEAD }}'
    foreground = 'p:text'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'git'
    style = 'powerline'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = false
      fetch_upstream_icon = false
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '
